---
title: "Fitting a model: Examples"
author: "Zach"
date: 2019-08-02
output:
  github_document
---

```{r }
library(tidyverse)
library(modelr)
```

```{r }
set.seed(103)
n <- 20

color_values <-
  c(
    "Truth" = "grey80",
    "Measurement" = "black",
    "Residual" = "deeppink",
    "Model" = "lightslateblue"
  )

df_data <-
  tibble(x = seq(0, 1, length.out = n)) %>%
  mutate(
    y = x^2,
    y_meas = y + 0.2 * rnorm(n = n),
    y_mean = mean(y)
  )

fit_linear <-
  lm(
    data = df_data,
    formula = y_meas ~ x
  )

fit_quad <-
  lm(
    data = df_data,
    formula = y_meas ~ poly(x, degree = 2)
  )
```

## Basic fits
<!-- -------------------------------------------------- -->

```{r }
df_data %>%
  ggplot() +
  geom_line(
    aes(x, y, color = "Truth"),
    size = 1 / 2
  ) +
  geom_segment(
    aes(x, y_meas, xend = x, yend = y, color = "Residual"),
    linetype = 1,
    size = 1
  ) +
  geom_point(
    aes(x, y_meas, color = "Measurement"),
    size = 3
  ) +
  scale_x_continuous(breaks = c(0, 1/2, 1)) +
  scale_y_continuous(breaks = c(0, 1/2, 1)) +
  scale_color_manual(
    name = "",
    values = color_values
  ) +
  theme_minimal() +
  theme(legend.position = "bottom") +
  labs(
    x = "Feature",
    y = "Response"
  )
ggsave("../../fig/06_model_fit_true.png")
```

```{r }
df_data %>%
  ggplot() +
  geom_line(
    aes(x, y_mean, color = "Model"),
    size = 1 / 2
  ) +
  geom_segment(
    aes(x, y_meas, xend = x, yend = y_mean, color = "Residual"),
    linetype = 1,
    size = 1
  ) +
  geom_point(
    aes(x, y_meas, color = "Measurement"),
    size = 3
  ) +
  scale_x_continuous(breaks = c(0, 1/2, 1)) +
  scale_y_continuous(breaks = c(0, 1/2, 1)) +
  scale_color_manual(
    name = "",
    values = color_values
  ) +
  theme_minimal() +
  theme(legend.position = "bottom") +
  labs(
    x = "Feature",
    y = "Response"
  )
ggsave("../../fig/06_model_fit_mean.png")
```

## Over/under fits
<!-- -------------------------------------------------- -->

```{r }
df_data %>%
  add_predictions(fit_linear, var = "y_pred") %>%
  ggplot() +
  geom_line(
    aes(x, y, color = "Truth"),
    size = 1 / 2
  ) +
  geom_line(
    aes(x, y_pred, color = "Model"),
    size = 1 / 2
  ) +
  geom_segment(
    aes(x, y_meas, xend = x, yend = y_pred, color = "Residual"),
    size = 1
  ) +
  geom_point(
    aes(x, y_meas, color = "Measurement"),
    size = 3
  ) +
  scale_x_continuous(breaks = c(0, 1/2, 1)) +
  scale_y_continuous(breaks = c(0, 1/2, 1)) +
  scale_color_manual(
    name = "",
    values = color_values
  ) +
  theme_minimal() +
  theme(legend.position = "bottom") +
  labs(
    x = "Feature",
    y = "Response"
  )
ggsave("../../fig/06_model_fit_linear.png")
```

```{r }
fit_linear_noiseless <-
  lm(
    data = df_data,
    formula = y ~ x
  )

df_data %>%
  add_predictions(fit_linear_noiseless, var = "y_pred") %>%
  ggplot() +
  geom_line(
    aes(x, y, color = "Truth"),
    size = 1 / 2,
  ) +
  geom_line(
    aes(x, y_pred, color = "Model"),
    size = 1 / 2
  ) +
  geom_segment(
    aes(x, y, xend = x, yend = y_pred, color = "Residual"),
    linetype = 1,
    size = 1,
    color = "red"
  ) +
  geom_point(
    aes(x, y, color = "Measurement"),
    size = 3
  ) +
  scale_x_continuous(breaks = c(0, 1/2, 1)) +
  scale_y_continuous(breaks = c(0, 1/2, 1)) +
  scale_color_manual(
    name = "",
    values = color_values
  ) +
  theme_minimal() +
  theme(legend.position = "bottom") +
  labs(
    x = "Feature",
    y = "Response"
  )
ggsave("../../fig/06_model_fit_linear_noiseless.png")
```

```{r }
df_data %>%
  add_predictions(fit_quad, var = "y_pred") %>%
  ggplot() +
  geom_line(
    aes(x, y, color = "Truth"),
    size = 1 / 2
  ) +
  geom_line(
    aes(x, y_pred, color = "Model"),
    size = 1 / 2
  ) +
  geom_segment(
    aes(x, y_meas, xend = x, yend = y_pred, color = "Residual"),
    linetype = 1,
    size = 1
  ) +
  geom_point(
    aes(x, y_meas, color = "Measurement"),
    size = 3
  ) +
  scale_x_continuous(breaks = c(0, 1/2, 1)) +
  scale_y_continuous(breaks = c(0, 1/2, 1)) +
  scale_color_manual(
    name = "",
    values = color_values
  ) +
  theme_minimal() +
  theme(legend.position = "bottom") +
  labs(
    x = "Feature",
    y = "Response"
  )
ggsave("../../fig/06_model_fit_quad.png")
```

```{r }
fit_poly <-
  lm(
    data = df_data,
    formula = y_meas ~ poly(x, degree = 14)
  )

df_ref <-
  tibble(x = seq(0, 1, length.out = 500)) %>%
  add_predictions(fit_poly, var = "y_pred")

df_data %>%
  add_predictions(fit_poly, var = "y_pred") %>%
  ggplot() +
  geom_line(
    aes(x, y, color = "Truth"),
    size = 1 / 2
  ) +
  geom_line(
    data = df_ref,
    aes(x, y_pred, color = "Model"),
    size = 1 / 2
  ) +
  geom_segment(
    aes(x, y_meas, xend = x, yend = y_pred, color = "Residual"),
    size = 1
  ) +
  geom_point(
    aes(x, y_meas, color = "Measurement"),
    size = 3
  ) +
  scale_x_continuous(breaks = c(0, 1/2, 1)) +
  scale_y_continuous(breaks = c(0, 1/2, 1)) +
  scale_color_manual(
    name = "",
    values = color_values
  ) +
  theme_minimal() +
  theme(legend.position = "bottom") +
  labs(
    x = "Feature",
    y = "Response"
  )
ggsave("../../fig/06_model_fit_overfit.png")
```

## Cross-validation fits
<!-- -------------------------------------------------- -->

```{r }
set.seed(101)
df_folds <- crossv_kfold(df_data, k = 5)

do_cv <- function(order) {
  pmap_dfr(
    df_folds,
    function(train, test, .id) {
      fit <- lm(formula = y_meas ~ poly(x, order), data = train)

      tibble(
        id = .id,
        rmse = rmse(fit, test),
        order = order
      )
    }
  )
}

df_cv <- map_dfr(seq(1, 8), do_cv)

df_cv %>%
  ggplot(aes(order, rmse)) +
  ## geom_boxplot(aes(group = order)) +
  geom_smooth(se = F, size = 2) +
  geom_point(
    position = position_jitter(width = 0.1, height = 0),
    size = 3,
    pch = 21,
    fill = "grey70",
    color = "black"
  ) +
  scale_x_continuous(breaks = seq(1,10)) +
  theme_minimal() +
  labs(
    x = "Polynomial Order",
    y = "RMSE"
  )
ggsave("../../fig/06_model_fit_cv.png")
```
